swagger: '2.0'
info:
  title: Express API
  description: API description in Markdown.
  version: 1.0.0
host: http://localhost:3000/
basePath: /v1
schemes:
  - https
paths:
  /users:
    get:
      tags: [users]
      summary: Returns a list of users.
      description: Optional extended description in Markdown.
      produces:
        - application/json
      responses:
        200:
          description: OK
